### ISSUE TITLE
查询时出现错误

### ISSUE THREAD

**Issue by Wickscc** [sea-team/gofound#34]
![image](https://user-images.githubusercontent.com/29065905/173772118-dfce2571-ae8f-4d76-b825-c887404a97f5.png)
通过 API 接口批量插入数据过后查询抛出异常
版本 1.16

**Comment by XiaoK29** [comment]
> ![image](https://user-images.githubusercontent.com/29065905/173772118-dfce2571-ae8f-4d76-b825-c887404a97f5.png) 通过 API 接口批量插入数据过后查询抛出异常 版本 1.16

有时间的时候我看看

**Comment by XiaoK29** [comment]
更新到最新版试试
