### ISSUE TITLE
web访问admin出现错误：index.3e4347a8.js  返回MIME类型为 “text/plain”

### ISSUE THREAD

**Issue by brucewang585** [sea-team/gofound#43]
详细错误提示：
index.3e4347a8.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.

添加代码  gofound/web/admin/admin.go：
import (
	"mime"
)

func init() {
	mime.AddExtensionType(".html", "text/html")
	mime.AddExtensionType(".css", "text/css")
	mime.AddExtensionType(".js", "text/javascript")
}

**Comment by newpanjing** [comment]
换linux
