### ISSUE TITLE
升级1.17后搜索结果重复出现

### ISSUE THREAD

**Issue by liiayy** [sea-team/gofound#55]
data目录数据不变，下载运行1.17后出现搜索结果重复，退回旧版本后恢复

**Comment by Tom-debug110** [comment]
可否提供一下运行截图呢，方便定位问题

**Comment by liiayy** [comment]
![Uploading image.png…]()

**Comment by liiayy** [comment]
![image](https://user-images.githubusercontent.com/71431109/183720445-100d70ad-ede2-47da-b5aa-81fe9ddfbc9e.png)
